### ISSUE TITLE
Source branches containing `/` not supported

### ISSUE THREAD

**Issue by durka** [krobelus/gitlab-offline-review#1]
When attempting to fetch a merge request whose source branch contains a slash, `parse_path` mangles the branch name by keeping just the "basename", so then the fetch fails with no error message because there is no such branch.

**Comment by krobelus** [comment]
Hi, thanks for reporting!
This should be fixed now; I have successfully posted a comment to a MR with a branch with slashes.
I hope there are not too many rough edges - I use this daily but some error messages are probably confusing
